// <auto-generated />
using System;
using GroceryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryManagement.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceryManagement.Models.Allocation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Allocation");
                });

            modelBuilder.Entity("GroceryManagement.Models.AttendanceRecords", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("StaffId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("GroceryManagement.Models.CustomerOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("CustomerOrder");
                });

            modelBuilder.Entity("GroceryManagement.Models.Expense", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("GroceryManagement.Models.Inventory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StaffId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("GroceryManagement.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("StoreFrontQty")
                        .HasColumnType("int");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WareHouseQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GroceryManagement.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GroceryManagement.Models.Manager", b =>
                {
                    b.HasBaseType("GroceryManagement.Models.User");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("GroceryManagement.Models.Staff", b =>
                {
                    b.HasBaseType("GroceryManagement.Models.User");

                    b.Property<string>("AuthorizationLvl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasIndex("ManagerId");

                    b.HasDiscriminator().HasValue("Staff");
                });

            modelBuilder.Entity("GroceryManagement.Models.Allocation", b =>
                {
                    b.HasOne("GroceryManagement.Models.Staff", null)
                        .WithMany("Allocations")
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("GroceryManagement.Models.AttendanceRecords", b =>
                {
                    b.HasOne("GroceryManagement.Models.Manager", null)
                        .WithMany("AttendenceRecords")
                        .HasForeignKey("ManagerId");

                    b.HasOne("GroceryManagement.Models.Staff", null)
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryManagement.Models.CustomerOrder", b =>
                {
                    b.HasOne("GroceryManagement.Models.Staff", null)
                        .WithMany("CustomerOrders")
                        .HasForeignKey("StaffId");
                });

            modelBuilder.Entity("GroceryManagement.Models.Expense", b =>
                {
                    b.HasOne("GroceryManagement.Models.Manager", "Manager")
                        .WithMany("Expenses")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GroceryManagement.Models.Inventory", b =>
                {
                    b.HasOne("GroceryManagement.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryManagement.Models.Staff", "Staff")
                        .WithMany("ManagedInventory")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GroceryManagement.Models.Staff", b =>
                {
                    b.HasOne("GroceryManagement.Models.Manager", "Manager")
                        .WithMany("Staffs")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GroceryManagement.Models.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("GroceryManagement.Models.Manager", b =>
                {
                    b.Navigation("AttendenceRecords");

                    b.Navigation("Expenses");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("GroceryManagement.Models.Staff", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("CustomerOrders");

                    b.Navigation("ManagedInventory");
                });
#pragma warning restore 612, 618
        }
    }
}
